// frontend/src/lib/components/ContactDetailsModal.svelte
<script lang="ts">
	import { createEventDispatcher, onMount } from 'svelte';
	import { goto } from '$app/navigation';

	export let contact: any;

	const dispatch = createEventDispatcher();

	let activeDebts = 0;
	let totalOwed = 0;
	let totalOwing = 0;

	onMount(() => {
		// Prevent body scroll when modal is open
		document.body.style.overflow = 'hidden';
		loadContactDebts();
		return () => {
			document.body.style.overflow = 'auto';
		};
	});

	function loadContactDebts() {
		// Mock data - replace with actual API call
		activeDebts = contact.debtCount || 0;
		totalOwed = contact.totalOwed || 0;
		totalOwing = contact.totalOwing || 0;
	}

	function formatDate(dateString: string): string {
		return new Date(dateString).toLocaleDateString('en-US', {
			month: 'long',
			day: 'numeric',
			year: 'numeric',
			hour: '2-digit',
			minute: '2-digit'
		});
	}

	function formatCurrency(amount: number): string {
		return new Intl.NumberFormat('en-PH', {
			style: 'currency',
			currency: 'PHP'
		}).format(amount);
	}

	function getTypeBadgeClass(type: string): string {
		return type === 'user_reference' 
			? 'bg-success/10 text-success' 
			: 'bg-primary/10 text-primary';
	}

	function closeModal() {
		dispatch('close');
	}

	function editContact() {
		dispatch('edit');
	}

	function deleteContact() {
		dispatch('delete');
	}

	function createDebtWithContact() {
		// Navigate to create debt page with contact pre-selected
		goto(`/debts/new?contactId=${contact.id}`);
		closeModal();
	}

	function viewAllDebts() {
		// Navigate to debts page filtered by this contact
		goto(`/debts?contactId=${contact.id}`);
		closeModal();
	}

	function handleKeydown(event: KeyboardEvent) {
		if (event.key === 'Escape') {
			closeModal();
		}
	}
</script>

<svelte:window on:keydown={handleKeydown} />

<!-- Modal Backdrop -->
<div class="fixed inset-0 bg-black/50 z-50 flex items-center justify-center p-4" on:click={closeModal}>
	<!-- Modal Content -->
	<div 
		class="bg-card rounded-xl shadow-medium max-w-3xl w-full max-h-[90vh] overflow-hidden flex flex-col"
		on:click|stopPropagation
	>
		<!-- Header -->
		<div class="px-6 py-4 border-b border-border">
			<div class="flex items-center justify-between">
				<div class="flex items-center space-x-4">
					<div class="w-12 h-12 bg-primary rounded-full flex items-center justify-center">
						<span class="text-primary-foreground font-medium">
							{contact.name.split(' ').map((n: string) => n[0]).join('')}
						</span>
					</div>
					<div>
						<h2 class="text-xl font-semibold text-foreground">{contact.name}</h2>
						<span class="inline-flex px-2 py-1 text-xs font-medium rounded-full {getTypeBadgeClass(contact.type)}">
							{contact.type === 'user_reference' ? 'User Reference' : 'Regular Contact'}
						</span>
					</div>
				</div>
				<button on:click={closeModal} class="text-muted-foreground hover:text-foreground">
					<svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
						<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"></path>
					</svg>
				</button>
			</div>
		</div>

		<!-- Content -->
		<div class="flex-1 overflow-y-auto">
			<div class="p-6 space-y-6">
				<!-- Contact Information -->
				<div class="grid grid-cols-1 md:grid-cols-2 gap-6">
					<!-- Personal Details -->
					<div class="space-y-4">
						<h3 class="text-lg font-medium text-foreground mb-4">Personal Details</h3>
						
						<div class="space-y-3">
							<div>
								<label class="block text-sm font-medium text-muted-foreground mb-1">Full Name</label>
								<div class="text-sm text-foreground font-medium">{contact.name}</div>
							</div>

							<div>
								<label class="block text-sm font-medium text-muted-foreground mb-1">Email Address</label>
								<div class="text-sm text-foreground">
									{#if contact.email}
										<a href="mailto:{contact.email}" class="text-primary hover:text-primary/80 flex items-center space-x-2">
											<svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
												<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 8l7.89 5.26a2 2 0 002.22 0L21 8M5 19h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z"></path>
											</svg>
											<span>{contact.email}</span>
										</a>
									{:else}
										<span class="text-muted-foreground">Not provided</span>
									{/if}
								</div>
							</div>

							<div>
								<label class="block text-sm font-medium text-muted-foreground mb-1">Phone Number</label>
								<div class="text-sm text-foreground">
									{#if contact.phone}
										<a href="tel:{contact.phone}" class="text-primary hover:text-primary/80 flex items-center space-x-2">
											<svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
												<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 5a2 2 0 012-2h3.28a1 1 0 01.948.684l1.498 4.493a1 1 0 01-.502 1.21l-2.257 1.13a11.042 11.042 0 005.516 5.516l1.13-2.257a1 1 0 011.21-.502l4.493 1.498a1 1 0 01.684.949V19a2 2 0 01-2 2h-1C9.716 21 3 14.284 3 6V5z"></path>
											</svg>
											<span>{contact.phone}</span>
										</a>
									{:else}
										<span class="text-muted-foreground">Not provided</span>
									{/if}
								</div>
							</div>

							{#if contact.notes}
								<div>
									<label class="block text-sm font-medium text-muted-foreground mb-1">Notes</label>
									<div class="text-sm text-foreground bg-muted/50 p-3 rounded-lg">{contact.notes}</div>
								</div>
							{/if}
						</div>
					</div>

					<!-- System Information -->
					<div class="space-y-4">
						<h3 class="text-lg font-medium text-foreground mb-4">System Information</h3>
						
						<div class="space-y-3">
							<div>
								<label class="block text-sm font-medium text-muted-foreground mb-1">Created Date</label>
								<div class="text-sm text-foreground">{formatDate(contact.createdAt)}</div>
							</div>

							<div>
								<label class="block text-sm font-medium text-muted-foreground mb-1">Last Updated</label>
								<div class="text-sm text-foreground">{formatDate(contact.updatedAt)}</div>
							</div>

							<div>
								<label class="block text-sm font-medium text-muted-foreground mb-1">Contact Type</label>
								<div class="text-sm">
									<span class="inline-flex px-3 py-1 text-sm font-medium rounded-full {getTypeBadgeClass(contact.type)}">
										{contact.type === 'user_reference' ? 'User Reference' : 'Regular Contact'}
									</span>
								</div>
							</div>

							{#if contact.type === 'user_reference'}
								<div>
									<label class="block text-sm font-medium text-muted-foreground mb-1">User Reference</label>
									<div class="text-sm text-foreground">
										<span class="text-primary">Linked to system user</span>
									</div>
								</div>
							{/if}
						</div>
					</div>
				</div>

				<!-- Debt Summary -->
				<div class="border-t border-border pt-6">
					<h3 class="text-lg font-medium text-foreground mb-4">Debt Summary</h3>
					
					<div class="grid grid-cols-1 md:grid-cols-3 gap-4 mb-6">
						<div class="card p-4">
							<div class="flex items-center justify-between">
								<div>
									<p class="text-sm font-medium text-muted-foreground">Active Debts</p>
									<p class="text-2xl font-bold text-foreground">{activeDebts}</p>
								</div>
								<div class="w-10 h-10 bg-primary/10 rounded-lg flex items-center justify-center">
									<svg class="w-5 h-5 text-primary" fill="none" stroke="currentColor" viewBox="0 0 24 24">
										<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2"></path>
									</svg>
								</div>
							</div>
						</div>

						<div class="card p-4">
							<div class="flex items-center justify-between">
								<div>
									<p class="text-sm font-medium text-muted-foreground">They Owe You</p>
									<p class="text-2xl font-bold text-success">{formatCurrency(totalOwed)}</p>
								</div>
								<div class="w-10 h-10 bg-success/10 rounded-lg flex items-center justify-center">
									<svg class="w-5 h-5 text-success" fill="none" stroke="currentColor" viewBox="0 0 24 24">
										<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 7h8m0 0v8m0-8l-8 8-4-4-6 6"></path>
									</svg>
								</div>
							</div>
						</div>

						<div class="card p-4">
							<div class="flex items-center justify-between">
								<div>
									<p class="text-sm font-medium text-muted-foreground">You Owe Them</p>
									<p class="text-2xl font-bold text-destructive">{formatCurrency(totalOwing)}</p>
								</div>
								<div class="w-10 h-10 bg-destructive/10 rounded-lg flex items-center justify-center">
									<svg class="w-5 h-5 text-destructive" fill="none" stroke="currentColor" viewBox="0 0 24 24">
										<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 17h8m0 0V9m0 8l-8-8-4 4-6-6"></path>
									</svg>
								</div>
							</div>
						</div>
					</div>

					<!-- Quick Actions -->
					<div class="grid grid-cols-1 md:grid-cols-2 gap-4">
						<button 
							on:click={createDebtWithContact}
							class="flex items-center justify-center space-x-2 p-4 bg-primary/10 hover:bg-primary/20 rounded-lg transition-colors duration-200"
						>
							<svg class="w-5 h-5 text-primary" fill="none" stroke="currentColor" viewBox="0 0 24 24">
								<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 6v6m0 0v6m0-6h6m-6 0H6"></path>
							</svg>
							<span class="font-medium text-primary">Create New Debt</span>
						</button>

						{#if activeDebts > 0}
							<button 
								on:click={viewAllDebts}
								class="flex items-center justify-center space-x-2 p-4 bg-secondary/10 hover:bg-secondary/20 rounded-lg transition-colors duration-200"
							>
								<svg class="w-5 h-5 text-secondary-foreground" fill="none" stroke="currentColor" viewBox="0 0 24 24">
									<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2"></path>
								</svg>
								<span class="font-medium text-secondary-foreground">View All Debts</span>
							</button>
						{/if}
					</div>
				</div>
			</div>
		</div>

		<!-- Footer Actions -->
		<div class="px-6 py-4 border-t border-border flex items-center justify-between">
			<div class="flex items-center space-x-3">
				<button on:click={editContact} class="btn-secondary">
					<svg class="w-4 h-4 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
						<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z"></path>
					</svg>
					Edit Contact
				</button>
				<button on:click={deleteContact} class="btn-danger">
					<svg class="w-4 h-4 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
						<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16"></path>
					</svg>
					Delete Contact
				</button>
			</div>
			<button on:click={closeModal} class="btn-primary">
				Close
			</button>
		</div>
	</div>
</div>

// frontend/src/components/contacts/ContactDetailsModal.jsx
import { useEffect } from 'react'

export const ContactDetailsModal = ({ contact, onClose, onEdit, onDelete }) => {
  useEffect(() => {
    document.body.style.overflow = 'hidden'
    return () => {
      document.body.style.overflow = 'auto'
    }
  }, [])

  useEffect(() => {
    const handleEscape = (e) => {
      if (e.key === 'Escape') onClose()
    }
    window.addEventListener('keydown', handleEscape)
    return () => window.removeEventListener('keydown', handleEscape)
  }, [onClose])

  const formatDate = (dateString) => {
    return new Date(dateString).toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
    })
  }

  const getInitials = (name) => {
    return name
      .split(' ')
      .map((n) => n[0])
      .join('')
      .toUpperCase()
  }

  return (
    <div
      className="fixed inset-0 z-50 !mt-0 flex items-start justify-center overflow-y-auto bg-black/60 p-4"
      onClick={onClose}
    >
      <div
        className="my-8 w-full max-w-lg rounded-xl bg-card shadow-medium"
        onClick={(e) => e.stopPropagation()}
      >
        <div className="flex items-center justify-between border-b border-border px-6 py-4">
          <h2 className="text-xl font-semibold text-foreground">Contact Details</h2>
          <button onClick={onClose} className="text-muted-foreground hover:text-foreground">
            <svg className="h-6 w-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth="2"
                d="M6 18L18 6M6 6l12 12"
              />
            </svg>
          </button>
        </div>

        <div className="p-6">
          {/* Contact Header */}
          <div className="mb-6 flex items-center space-x-4">
            <div className="flex h-16 w-16 items-center justify-center rounded-full bg-primary">
              <span className="text-xl font-medium text-primary-foreground">
                {getInitials(contact.name)}
              </span>
            </div>
            <div>
              <h3 className="text-2xl font-bold text-foreground">{contact.name}</h3>
              <span className="inline-flex rounded-full bg-primary/10 px-2 py-1 text-xs font-medium text-primary">
                Regular Contact
              </span>
            </div>
          </div>

          {/* Contact Information */}
          <div className="space-y-4">
            {contact.email && (
              <div className="flex items-start space-x-3">
                <svg
                  className="mt-0.5 h-5 w-5 text-muted-foreground"
                  fill="none"
                  stroke="currentColor"
                  viewBox="0 0 24 24"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth="2"
                    d="M3 8l7.89 5.26a2 2 0 002.22 0L21 8M5 19h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z"
                  />
                </svg>
                <div>
                  <p className="text-sm font-medium text-muted-foreground">Email</p>
                  <p className="text-foreground">{contact.email}</p>
                </div>
              </div>
            )}

            {contact.phone && (
              <div className="flex items-start space-x-3">
                <svg
                  className="mt-0.5 h-5 w-5 text-muted-foreground"
                  fill="none"
                  stroke="currentColor"
                  viewBox="0 0 24 24"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth="2"
                    d="M3 5a2 2 0 012-2h3.28a1 1 0 01.948.684l1.498 4.493a1 1 0 01-.502 1.21l-2.257 1.13a11.042 11.042 0 005.516 5.516l1.13-2.257a1 1 0 011.21-.502l4.493 1.498a1 1 0 01.684.949V19a2 2 0 01-2 2h-1C9.716 21 3 14.284 3 6V5z"
                  />
                </svg>
                <div>
                  <p className="text-sm font-medium text-muted-foreground">Phone</p>
                  <p className="text-foreground">{contact.phone}</p>
                </div>
              </div>
            )}

            {contact.notes && (
              <div className="flex items-start space-x-3">
                <svg
                  className="mt-0.5 h-5 w-5 text-muted-foreground"
                  fill="none"
                  stroke="currentColor"
                  viewBox="0 0 24 24"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth="2"
                    d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"
                  />
                </svg>
                <div>
                  <p className="text-sm font-medium text-muted-foreground">Notes</p>
                  <p className="text-foreground">{contact.notes}</p>
                </div>
              </div>
            )}

            <div className="flex items-start space-x-3">
              <svg
                className="mt-0.5 h-5 w-5 text-muted-foreground"
                fill="none"
                stroke="currentColor"
                viewBox="0 0 24 24"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth="2"
                  d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z"
                />
              </svg>
              <div>
                <p className="text-sm font-medium text-muted-foreground">Created</p>
                <p className="text-foreground">{formatDate(contact.created_at)}</p>
              </div>
            </div>

            {contact.updated_at !== contact.created_at && (
              <div className="flex items-start space-x-3">
                <svg
                  className="mt-0.5 h-5 w-5 text-muted-foreground"
                  fill="none"
                  stroke="currentColor"
                  viewBox="0 0 24 24"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth="2"
                    d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15"
                  />
                </svg>
                <div>
                  <p className="text-sm font-medium text-muted-foreground">Last Updated</p>
                  <p className="text-foreground">{formatDate(contact.updated_at)}</p>
                </div>
              </div>
            )}
          </div>

          {/* Action Buttons */}
          <div className="mt-6 flex items-center justify-end space-x-3 border-t border-border pt-4">
            <button onClick={onDelete} className="btn-destructive">
              Delete
            </button>
            <button onClick={onEdit} className="btn-primary">
              Edit
            </button>
          </div>
        </div>
      </div>
    </div>
  )
}
