// frontend/src/components/debts/DebtDetailsModal.jsx
import { useState, useEffect } from 'react'
import { usePaymentsStore } from '@stores/paymentsStore'
import {
  formatCurrency,
  formatDate,
  formatRelativeTime,
  getDaysUntilDue,
  getDueDateColor,
} from '@utils/formatters'

export const DebtDetailsModal = ({ debt, onClose, onEdit, onDelete }) => {
  const {
    fetchPayments,
    createPayment,
    uploadReceipt,
    isLoading: paymentsLoading,
  } = usePaymentsStore()
  const [debtPayments, setDebtPayments] = useState([])
  const [showAddPayment, setShowAddPayment] = useState(false)
  const [newPayment, setNewPayment] = useState({
    payment_date: new Date().toISOString().split('T')[0],
    amount: '',
    description: '',
  })
  const [receiptFile, setReceiptFile] = useState(null)
  const [isSubmitting, setIsSubmitting] = useState(false)
  const [viewingReceipt, setViewingReceipt] = useState(null)
  const [imageError, setImageError] = useState(false)
  const [imageBlob, setImageBlob] = useState(null)
  const [imageLoading, setImageLoading] = useState(false)

  useEffect(() => {
    loadPayments(debt.id)
  }, [debt.id])

  // Fetch receipt image with authorization header
  useEffect(() => {
    let isMounted = true
    let objectUrl = null

    const fetchReceiptImage = async () => {
      if (!viewingReceipt?.receipt_photo_url) return

      setImageLoading(true)
      setImageError(false)
      setImageBlob(null)

      try {
        const token = localStorage.getItem('token')
        const response = await fetch(viewingReceipt.receipt_photo_url, {
          headers: token ? { Authorization: `Bearer ${token}` } : {},
        })

        if (!response.ok) {
          throw new Error('Failed to load image')
        }

        const blob = await response.blob()
        objectUrl = URL.createObjectURL(blob)

        if (isMounted) {
          setImageBlob(objectUrl)
        } else {
          // Component unmounted before fetch completed, cleanup immediately
          URL.revokeObjectURL(objectUrl)
        }
      } catch (error) {
        console.error('Failed to load receipt image:', error)
        if (isMounted) {
          setImageError(true)
        }
      } finally {
        if (isMounted) {
          setImageLoading(false)
        }
      }
    }

    if (viewingReceipt) {
      fetchReceiptImage()
    } else {
      // Reset states when modal is closed
      setImageBlob(null)
      setImageError(false)
      setImageLoading(false)
    }

    // Cleanup blob URL when component unmounts or viewingReceipt changes
    return () => {
      isMounted = false
      if (objectUrl) {
        URL.revokeObjectURL(objectUrl)
      }
    }
  }, [viewingReceipt])

  const loadPayments = async (debtId) => {
    console.log('debtId', debtId)
    try {
      const paymentsData = await fetchPayments(debtId)
      setDebtPayments(paymentsData || [])
    } catch (error) {
      console.error('Failed to load payments:', error)
      setDebtPayments([])
    }
  }

  const handleAddPayment = async (e) => {
    e.preventDefault()
    if (!newPayment.amount || parseFloat(newPayment.amount) <= 0) {
      alert('Please enter a valid amount')
      return
    }

    try {
      setIsSubmitting(true)
      // Convert date string to ISO 8601 datetime format
      const paymentDateTime = new Date(newPayment.payment_date + 'T12:00:00Z').toISOString()

      const payment = await createPayment(debt.id, {
        payment_date: paymentDateTime,
        amount: String(newPayment.amount),
        description: newPayment.description,
      })

      // Upload receipt if file is selected
      if (receiptFile && payment.id) {
        await uploadReceipt(payment.id, receiptFile)
      }

      // Reload payments
      await loadPayments(payment.debt_list_id)

      // Reset form
      setNewPayment({
        payment_date: new Date().toISOString().split('T')[0],
        amount: '',
        description: '',
      })
      setReceiptFile(null)
      setShowAddPayment(false)
    } catch (error) {
      console.error('Failed to add payment:', error)
      alert('Failed to add payment. Please try again.')
    } finally {
      setIsSubmitting(false)
    }
  }

  const handleFileChange = (e) => {
    const file = e.target.files?.[0]
    if (file) {
      // Validate file type
      const validTypes = ['image/jpeg', 'image/png', 'image/jpg', 'image/webp']
      if (!validTypes.includes(file.type)) {
        alert('Please select a valid image file (JPEG, PNG, or WebP)')
        return
      }
      // Validate file size (max 5MB)
      if (file.size > 5 * 1024 * 1024) {
        alert('File size must be less than 5MB')
        return
      }
      setReceiptFile(file)
    }
  }

  const handleOverlayClick = (e) => {
    if (e.target === e.currentTarget) {
      onClose()
    }
  }

  const daysUntilDue = getDaysUntilDue(debt.due_date)
  // Calculate total paid and remaining balance
  const totalPaid = debtPayments.reduce((sum, payment) => sum + parseFloat(payment.amount || 0), 0)
  const remainingBalance = parseFloat(debt.total_amount || 0) - totalPaid

  return (
    <div
      className="fixed inset-0 z-50 !mt-0 flex items-start justify-center overflow-y-auto bg-black/60 p-4"
      onClick={handleOverlayClick}
    >
      <div className="card my-8 w-full max-w-2xl overflow-hidden">
        <div className="border-b border-border px-6 py-4">
          <div className="flex items-center justify-between">
            <h2 className="text-xl font-semibold text-foreground">Debt Details</h2>
            <button
              onClick={onClose}
              className="text-muted-foreground transition-colors hover:text-foreground"
            >
              <svg className="h-6 w-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth="2"
                  d="M6 18L18 6M6 6l12 12"
                />
              </svg>
            </button>
          </div>
        </div>

        <div className="p-6">
          <div className="space-y-6">
            {/* Debt Type Badge */}
            <div className="flex items-center justify-between">
              <span
                className={`inline-flex rounded-full px-3 py-1 text-sm font-medium ${
                  debt.debt_type === 'i_owe'
                    ? 'bg-destructive/10 text-destructive'
                    : 'bg-success/10 text-success'
                }`}
              >
                {debt.debt_type === 'i_owe' ? 'I Owe' : 'Owed to Me'}
              </span>
              <div className="text-sm text-muted-foreground">
                Updated {formatRelativeTime(debt.updated_at)}
              </div>
            </div>

            {/* Amount Section */}
            <div className="rounded-lg border border-border bg-muted/50 p-6">
              <div className="grid grid-cols-1 gap-4 md:grid-cols-3">
                <div className="text-center">
                  <div className="mb-2 text-sm text-muted-foreground">Total Amount</div>
                  <div
                    className={`text-2xl font-bold ${
                      debt.debt_type === 'i_owe' ? 'text-destructive' : 'text-success'
                    }`}
                  >
                    {formatCurrency(parseFloat(debt.total_amount || 0))}
                  </div>
                </div>
                <div className="text-center">
                  <div className="mb-2 text-sm text-muted-foreground">Total Paid</div>
                  <div className="text-2xl font-bold text-primary">{formatCurrency(totalPaid)}</div>
                </div>
                <div className="text-center">
                  <div className="mb-2 text-sm text-muted-foreground">Remaining</div>
                  <div
                    className={`text-2xl font-bold ${
                      remainingBalance > 0
                        ? debt.debt_type === 'i_owe'
                          ? 'text-destructive'
                          : 'text-success'
                        : 'text-muted-foreground'
                    }`}
                  >
                    {formatCurrency(remainingBalance)}
                  </div>
                </div>
              </div>
            </div>

            {/* Contact Information */}
            <div className="rounded-lg border border-border p-4">
              <div className="mb-2 text-sm font-medium text-muted-foreground">Contact</div>
              <div className="flex items-center space-x-3">
                <div className="flex h-12 w-12 items-center justify-center rounded-full bg-primary/10">
                  <span className="text-lg font-medium text-primary">
                    {debt.contact?.name
                      ?.split(' ')
                      .map((n) => n[0])
                      .join('')
                      .toUpperCase() || 'U'}
                  </span>
                </div>
                <div>
                  <div className="font-medium text-foreground">
                    {debt.contact?.name || 'Unknown Contact'}
                  </div>
                  {debt.contact?.email && (
                    <div className="text-sm text-muted-foreground">{debt.contact.email}</div>
                  )}
                  {debt.contact?.phone && (
                    <div className="text-sm text-muted-foreground">{debt.contact.phone}</div>
                  )}
                </div>
              </div>
            </div>

            {/* Description */}
            <div className="rounded-lg border border-border p-4">
              <div className="mb-2 text-sm font-medium text-muted-foreground">Description</div>
              <div className="text-foreground">{debt.description || 'No description provided'}</div>
            </div>

            {/* Due Date */}
            {debt.due_date && (
              <div className="rounded-lg border border-border p-4">
                <div className="mb-2 text-sm font-medium text-muted-foreground">Due Date</div>
                <div className="flex items-center justify-between">
                  <div className="text-foreground">{formatDate(debt.due_date)}</div>
                  {daysUntilDue !== null && (
                    <span className={`text-sm font-medium ${getDueDateColor(daysUntilDue)}`}>
                      {daysUntilDue < 0
                        ? `Overdue by ${Math.abs(daysUntilDue)} days`
                        : daysUntilDue === 0
                          ? 'Due today'
                          : `Due in ${daysUntilDue} days`}
                    </span>
                  )}
                </div>
              </div>
            )}

            {/* Notes */}
            {debt.notes && (
              <div className="rounded-lg border border-border p-4">
                <div className="mb-2 text-sm font-medium text-muted-foreground">Notes</div>
                <div className="whitespace-pre-wrap text-foreground">{debt.notes}</div>
              </div>
            )}

            {/* Payment History */}
            <div className="rounded-lg border border-border">
              <div className="border-b border-border p-4">
                <div className="mb-3 flex items-center justify-between">
                  <div className="text-sm font-medium text-muted-foreground">
                    Payment History ({debtPayments.length})
                  </div>
                  <button
                    onClick={() => setShowAddPayment(!showAddPayment)}
                    className="text-sm text-primary hover:text-primary/80"
                  >
                    {showAddPayment ? '− Cancel' : '+ Add Payment'}
                  </button>
                </div>

                {/* Add Payment Form */}
                {showAddPayment && (
                  <form
                    onSubmit={handleAddPayment}
                    className="mt-3 space-y-3 rounded-lg bg-muted/30 p-3"
                  >
                    <div className="grid grid-cols-1 gap-3 sm:grid-cols-2">
                      <div>
                        <label className="mb-1 block text-xs font-medium text-muted-foreground">
                          Payment Date
                        </label>
                        <input
                          type="date"
                          value={newPayment.payment_date}
                          onChange={(e) =>
                            setNewPayment({ ...newPayment, payment_date: e.target.value })
                          }
                          className="input"
                          required
                        />
                      </div>
                      <div>
                        <label className="mb-1 block text-xs font-medium text-muted-foreground">
                          Amount
                        </label>
                        <input
                          type="number"
                          step="0.01"
                          min="0"
                          value={newPayment.amount}
                          onChange={(e) => setNewPayment({ ...newPayment, amount: e.target.value })}
                          className="input"
                          placeholder="0.00"
                          required
                        />
                      </div>
                    </div>
                    <div>
                      <label className="mb-1 block text-xs font-medium text-muted-foreground">
                        Description (Optional)
                      </label>
                      <input
                        type="text"
                        value={newPayment.description}
                        onChange={(e) =>
                          setNewPayment({ ...newPayment, description: e.target.value })
                        }
                        className="input"
                        placeholder="Payment description..."
                      />
                    </div>
                    <div>
                      <label className="mb-1 block text-xs font-medium text-muted-foreground">
                        Receipt Photo (Optional)
                      </label>
                      <input
                        type="file"
                        accept="image/jpeg,image/png,image/jpg,image/webp"
                        onChange={handleFileChange}
                        className="input"
                      />
                      {receiptFile && (
                        <div className="mt-1 text-xs text-muted-foreground">
                          Selected: {receiptFile.name}
                        </div>
                      )}
                    </div>
                    <div className="flex justify-end space-x-2">
                      <button
                        type="button"
                        onClick={() => {
                          setShowAddPayment(false)
                          setNewPayment({
                            payment_date: new Date().toISOString().split('T')[0],
                            amount: '',
                            description: '',
                          })
                          setReceiptFile(null)
                        }}
                        className="btn-secondary"
                        disabled={isSubmitting}
                      >
                        Cancel
                      </button>
                      <button type="submit" className="btn-primary" disabled={isSubmitting}>
                        {isSubmitting ? 'Adding...' : 'Add Payment'}
                      </button>
                    </div>
                  </form>
                )}
              </div>

              {paymentsLoading ? (
                <div className="py-8 text-center text-sm text-muted-foreground">
                  Loading payments...
                </div>
              ) : debtPayments.length === 0 ? (
                <div className="py-8 text-center text-sm text-muted-foreground">
                  No payments recorded yet
                </div>
              ) : (
                <div className="overflow-x-auto">
                  <table className="w-full">
                    <thead className="border-b border-border bg-muted/50">
                      <tr>
                        <th className="px-4 py-3 text-left text-xs font-medium text-muted-foreground">
                          Date
                        </th>
                        <th className="px-4 py-3 text-left text-xs font-medium text-muted-foreground">
                          Amount
                        </th>
                        <th className="px-4 py-3 text-left text-xs font-medium text-muted-foreground">
                          Description
                        </th>
                        <th className="px-4 py-3 text-center text-xs font-medium text-muted-foreground">
                          Status
                        </th>
                        <th className="px-4 py-3 text-center text-xs font-medium text-muted-foreground">
                          Receipt
                        </th>
                      </tr>
                    </thead>
                    <tbody className="divide-y divide-border">
                      {debtPayments
                        .sort((a, b) => new Date(b.payment_date) - new Date(a.payment_date))
                        .map((payment) => (
                          <tr key={payment.id} className="hover:bg-muted/30">
                            <td className="px-4 py-3 text-sm text-foreground">
                              {formatDate(payment.payment_date)}
                            </td>
                            <td className="px-4 py-3 text-sm font-medium text-foreground">
                              {formatCurrency(parseFloat(payment.amount || 0))}
                            </td>
                            <td className="px-4 py-3 text-sm text-muted-foreground">
                              {payment.description || '—'}
                            </td>
                            <td className="px-4 py-3 text-center">
                              <span
                                className={`inline-flex rounded-full px-2 py-1 text-xs font-medium ${
                                  payment.status === 'verified'
                                    ? 'bg-success/10 text-success'
                                    : payment.status === 'pending'
                                      ? 'bg-warning/10 text-warning'
                                      : payment.status === 'disputed'
                                        ? 'bg-destructive/10 text-destructive'
                                        : 'bg-muted/50 text-muted-foreground'
                                }`}
                              >
                                {payment.status || 'pending'}
                              </span>
                            </td>
                            <td className="px-4 py-3 text-center">
                              {payment.receipt_photo_url ? (
                                <button
                                  onClick={() => {
                                    setViewingReceipt(payment)
                                    setImageError(false)
                                  }}
                                  className="mx-auto inline-flex items-center justify-center rounded p-1 transition-colors hover:bg-primary/10"
                                  title="View receipt"
                                >
                                  <svg
                                    className="h-5 w-5 text-primary"
                                    fill="none"
                                    stroke="currentColor"
                                    viewBox="0 0 24 24"
                                  >
                                    <path
                                      strokeLinecap="round"
                                      strokeLinejoin="round"
                                      strokeWidth="2"
                                      d="M15.172 7l-6.586 6.586a2 2 0 102.828 2.828l6.414-6.586a4 4 0 00-5.656-5.656l-6.415 6.585a6 6 0 108.486 8.486L20.5 13"
                                    />
                                  </svg>
                                </button>
                              ) : (
                                <span className="text-muted-foreground/50">—</span>
                              )}
                            </td>
                          </tr>
                        ))}
                    </tbody>
                  </table>
                </div>
              )}
            </div>

            {/* Timestamps */}
            <div className="grid grid-cols-2 gap-4 rounded-lg border border-border p-4">
              <div>
                <div className="mb-1 text-sm font-medium text-muted-foreground">Created</div>
                <div className="text-sm text-foreground">{formatDate(debt.created_at)}</div>
              </div>
              <div>
                <div className="mb-1 text-sm font-medium text-muted-foreground">Last Updated</div>
                <div className="text-sm text-foreground">{formatDate(debt.updated_at)}</div>
              </div>
            </div>
          </div>

          {/* Action Buttons */}
          <div className="mt-6 flex space-x-3">
            <button onClick={onEdit} className="btn-secondary flex-1">
              <svg className="mr-2 h-4 w-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth="2"
                  d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z"
                />
              </svg>
              Edit
            </button>
            <button onClick={onDelete} className="btn-destructive flex-1">
              <svg className="mr-2 h-4 w-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth="2"
                  d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16"
                />
              </svg>
              Delete
            </button>
          </div>
        </div>
      </div>

      {/* Image Viewer Modal */}
      {viewingReceipt && (
        <div
          className="fixed inset-0 z-[60] flex items-center justify-center bg-black/80 p-4"
          onClick={() => setViewingReceipt(null)}
        >
          <div
            className="relative max-h-[90vh] max-w-4xl overflow-auto rounded-lg bg-card shadow-xl"
            onClick={(e) => e.stopPropagation()}
          >
            {/* Header */}
            <div className="flex items-center justify-between border-b border-border p-4">
              <div>
                <h3 className="text-lg font-semibold text-foreground">Payment Receipt</h3>
                <div className="mt-1 text-sm text-muted-foreground">
                  {formatDate(viewingReceipt.payment_date)} •{' '}
                  {formatCurrency(parseFloat(viewingReceipt.amount || 0))}
                </div>
              </div>
              <button
                onClick={() => setViewingReceipt(null)}
                className="text-muted-foreground transition-colors hover:text-foreground"
              >
                <svg className="h-6 w-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth="2"
                    d="M6 18L18 6M6 6l12 12"
                  />
                </svg>
              </button>
            </div>

            {/* Image Content */}
            <div className="p-4">
              {imageLoading ? (
                <div className="flex min-h-[300px] items-center justify-center">
                  <div className="text-center">
                    <svg
                      className="mx-auto h-12 w-12 animate-spin text-primary"
                      fill="none"
                      viewBox="0 0 24 24"
                    >
                      <circle
                        className="opacity-25"
                        cx="12"
                        cy="12"
                        r="10"
                        stroke="currentColor"
                        strokeWidth="4"
                      />
                      <path
                        className="opacity-75"
                        fill="currentColor"
                        d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"
                      />
                    </svg>
                    <div className="mt-3 text-sm text-muted-foreground">Loading receipt...</div>
                  </div>
                </div>
              ) : imageError ? (
                <div className="flex min-h-[300px] flex-col items-center justify-center space-y-4 text-center">
                  <svg
                    className="h-16 w-16 text-destructive"
                    fill="none"
                    stroke="currentColor"
                    viewBox="0 0 24 24"
                  >
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      strokeWidth="2"
                      d="M12 8v4m0 4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"
                    />
                  </svg>
                  <div>
                    <div className="text-lg font-medium text-foreground">Failed to load image</div>
                    <div className="mt-1 text-sm text-muted-foreground">
                      The receipt photo could not be loaded. It may have been deleted or is
                      temporarily unavailable.
                    </div>
                  </div>
                  <a
                    href={viewingReceipt.receipt_photo_url}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="btn-secondary"
                  >
                    Try opening in new tab
                  </a>
                </div>
              ) : imageBlob ? (
                <div className="flex items-center justify-center">
                  <img
                    src={imageBlob}
                    alt="Payment receipt"
                    className="max-h-[70vh] w-auto rounded object-contain"
                    onError={() => setImageError(true)}
                  />
                </div>
              ) : null}
            </div>

            {/* Footer with Actions */}
            {!imageError && !imageLoading && imageBlob && (
              <div className="border-t border-border p-4">
                <div className="flex justify-end space-x-2">
                  <button
                    onClick={() => {
                      if (imageBlob) {
                        window.open(imageBlob, '_blank')
                      }
                    }}
                    className="btn-secondary"
                  >
                    <svg
                      className="mr-2 h-4 w-4"
                      fill="none"
                      stroke="currentColor"
                      viewBox="0 0 24 24"
                    >
                      <path
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        strokeWidth="2"
                        d="M10 6H6a2 2 0 00-2 2v10a2 2 0 002 2h10a2 2 0 002-2v-4M14 4h6m0 0v6m0-6L10 14"
                      />
                    </svg>
                    Open in new tab
                  </button>
                  <a href={imageBlob} download="receipt.jpg" className="btn-primary">
                    <svg
                      className="mr-2 h-4 w-4"
                      fill="none"
                      stroke="currentColor"
                      viewBox="0 0 24 24"
                    >
                      <path
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        strokeWidth="2"
                        d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4"
                      />
                    </svg>
                    Download
                  </a>
                </div>
              </div>
            )}
          </div>
        </div>
      )}
    </div>
  )
}

// frontend/src/lib/components/DebtDetailsModal.svelte
<script lang="ts">
	import { createEventDispatcher, onMount } from 'svelte';
	import { apiClient, type Payment } from '../api';
	import ReceiptPhotoViewer from './ReceiptPhotoViewer.svelte';

	export let debt: any;

	const dispatch = createEventDispatcher();

	let payments: Payment[] = [];
	let showPaymentForm = false;
	let newPayment = {
		amount: '',
		payment_date: '',
		payment_method: 'cash',
		description: '',
		receiptPhoto: undefined as File | undefined
	};
	let isLoading = false;
	let error: string | null = null;

	// Receipt photo viewer state
	let showReceiptViewer = false;
	let selectedReceiptPhoto = '';

	console.log(debt);

	onMount(() => {
		loadPayments();
		// Prevent body scroll when modal is open
		document.body.style.overflow = 'hidden';
		return () => {
			document.body.style.overflow = 'auto';
		};
	});

	async function loadPayments() {
		if (!debt?.id) {
			console.error('No debt ID provided');
			error = 'No debt ID provided';
			payments = [];
			return;
		}

		isLoading = true;
		error = null;
		
		try {
			console.log('Loading payments for debt:', debt.id);
			payments = await apiClient.getPayments(debt.id);
			console.log('Loaded payments:', payments);
			
			// Filter out payments without valid IDs and ensure unique IDs
			payments = payments.filter(payment => payment.id && payment.id.trim() !== '');
			
			// Check for duplicate or undefined IDs
			const ids = payments.map(p => p.id);
			const uniqueIds = new Set(ids);
			if (ids.length !== uniqueIds.size) {
				console.warn('Duplicate payment IDs found:', ids);
				// Remove duplicates by keeping only the first occurrence
				const seen = new Set();
				payments = payments.filter(payment => {
					if (seen.has(payment.id)) {
						return false;
					}
					seen.add(payment.id);
					return true;
				});
			}
			if (ids.some(id => !id)) {
				console.warn('Some payments have undefined IDs:', payments.filter(p => !p.id));
			}
		} catch (err) {
			error = err instanceof Error ? err.message : 'Failed to load payments';
			console.error('Error loading payments:', err);
			// Set empty array on error to prevent UI issues
			payments = [];
		} finally {
			isLoading = false;
		}
	}

	function formatCurrency(amount: number | string, currency: string = 'PHP'): string {
		const numAmount = typeof amount === 'string' ? parseFloat(amount) : amount;
		return new Intl.NumberFormat('en-PH', {
			style: 'currency',
			currency: currency
		}).format(numAmount);
	}

	function formatDate(dateString: string): string {
		return new Date(dateString).toLocaleDateString('en-US', {
			month: 'short',
			day: 'numeric',
			year: 'numeric'
		});
	}

	function getStatusBadgeClass(status: string): string {
		switch (status) {
			case 'active':
				return 'bg-primary/10 text-primary';
			case 'settled':
				return 'bg-success/10 text-success';
			case 'archived':
				return 'bg-muted/50 text-muted-foreground';
			case 'overdue':
				return 'bg-destructive/10 text-destructive';
			default:
				return 'bg-muted/50 text-muted-foreground';
		}
	}

	function getPaymentStatusClass(status: string): string {
		switch (status) {
			case 'verified':
			case 'completed':
				return 'bg-success/10 text-success';
			case 'pending':
				return 'bg-warning/10 text-warning';
			case 'overdue':
				return 'bg-destructive/10 text-destructive';
			case 'rejected':
				return 'bg-destructive/10 text-destructive';
			default:
				return 'bg-muted/50 text-muted-foreground';
		}
	}

	// File validation
	function validateFile(file: File): string | null {
		const maxSize = 5 * 1024 * 1024; // 5MB
		const allowedTypes = ['image/jpeg', 'image/jpg', 'image/png', 'image/gif', 'image/webp'];
		
		if (file.size > maxSize) return 'File size must be less than 5MB';
		if (!allowedTypes.includes(file.type)) return 'Only image files are allowed';
		return null;
	}

	function handleFileSelect(event: Event) {
		const target = event.target as HTMLInputElement;
		if (target.files && target.files[0]) {
			const file = target.files[0];
			const error = validateFile(file);
			
			if (error) {
				alert(error);
				return;
			}
			
			newPayment.receiptPhoto = file;
		}
	}

	function removeReceiptPhoto() {
		newPayment.receiptPhoto = undefined;
	}

	function viewReceiptPhoto(photoURL: string) {
		selectedReceiptPhoto = photoURL;
		showReceiptViewer = true;
	}

	function getInstallmentText(plan: string): string {
		const plans = {
			'one_time': 'One-time',
			'weekly': 'Weekly',
			'biweekly': 'Bi-weekly',
			'monthly': 'Monthly',
			'quarterly': 'Quarterly',
			'yearly': 'Yearly'
		};
		return plans[plan as keyof typeof plans] || plan;
	}

	function calculateProgress(): number {
		const totalAmount = parseFloat(debt.total_amount);
		if (totalAmount === 0) return 100;
		const paid = totalAmount - debt.remainingBalance;
		return Math.round((paid / totalAmount) * 100);
	}

	async function handleAddPayment() {
		if (parseFloat(newPayment.amount) > 0 && newPayment.payment_date) {
			try {
				console.log('Creating payment:', newPayment);
				// Create the payment via API
				const payment = await apiClient.createPayment(debt.id, {
					amount: newPayment.amount,
					payment_date: newPayment.payment_date,
					payment_method: newPayment.payment_method,
					description: newPayment.description
				});

				console.log('Payment created:', payment);

				// Upload receipt photo if provided
				if (newPayment.receiptPhoto) {
					console.log('Uploading receipt photo');
					await apiClient.uploadReceipt(payment.id, newPayment.receiptPhoto);
				}

				// Reload payments to get updated data
				await loadPayments();
				
				// Reset form
				newPayment = {
					amount: '',
					payment_date: '',
					payment_method: 'cash',
					description: '',
					receiptPhoto: undefined
				};
				showPaymentForm = false;
			} catch (err) {
				error = err instanceof Error ? err.message : 'Failed to add payment';
				console.error('Error adding payment:', err);
			}
		} else {
			error = 'Please provide both amount and payment date';
		}
	}

	async function verifyPayment(paymentId: string) {
		try {
			console.log('Verifying payment:', paymentId);
			await apiClient.verifyPayment(paymentId);
			console.log('Payment verified successfully');
			// Reload payments to get updated data
			await loadPayments();
		} catch (err) {
			error = err instanceof Error ? err.message : 'Failed to verify payment';
			console.error('Error verifying payment:', err);
		}
	}

	function closeModal() {
		dispatch('close');
	}

	function editDebt() {
		dispatch('edit');
	}

	function deleteDebt() {
		dispatch('delete');
		closeModal();
	}

	function handleKeydown(event: KeyboardEvent) {
		if (event.key === 'Escape') {
			closeModal();
		}
	}
</script>

<svelte:window on:keydown={handleKeydown} />

<!-- Modal Backdrop -->
<div class="fixed inset-0 bg-black/50 z-50 flex items-center justify-center p-4" on:click={closeModal}>
	<!-- Modal Content -->
	<div 
		class="bg-card rounded-xl shadow-medium max-w-4xl w-full max-h-[90vh] overflow-hidden flex flex-col"
		on:click|stopPropagation
	>
		<!-- Header -->
		<div class="px-6 py-4 border-b border-border flex items-center justify-between">
			<div class="flex items-center space-x-4">
				<h2 class="text-xl font-semibold text-foreground">Debt Details</h2>
				<span class="inline-flex px-3 py-1 text-sm font-medium rounded-full {getStatusBadgeClass(debt.status)}">
					{debt.status.charAt(0).toUpperCase() + debt.status.slice(1)}
				</span>
			</div>
			<button on:click={closeModal} class="text-muted-foreground hover:text-foreground">
				<svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
					<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"></path>
				</svg>
			</button>
		</div>

		<!-- Content -->
		<div class="flex-1 overflow-y-auto">
			<div class="p-6 space-y-8">
				<!-- Debt Information -->
				<div class="grid grid-cols-1 lg:grid-cols-2 gap-8">
					<!-- Basic Details -->
					<div class="space-y-6">
						<div>
							<h3 class="text-lg font-medium text-foreground mb-4">Basic Information</h3>
							<div class="space-y-4">
								<div class="flex items-center space-x-4">
									<div class="w-12 h-12 bg-primary rounded-full flex items-center justify-center">
										<span class="text-primary-foreground font-medium">
											{debt.contactName.split(' ').map((n: string) => n[0]).join('')}
										</span>
									</div>
									<div>
										<div class="font-medium text-foreground">{debt.contactName}</div>
										<div class="text-sm text-muted-foreground">
											{debt.debt_type === 'owed_to_me' ? 'Owes you money' : 'You owe money to'}
										</div>
									</div>
								</div>

								<div class="grid grid-cols-2 gap-4">
									<div>
										<label class="block text-sm font-medium text-muted-foreground mb-1">Debt Type</label>
										<span class="inline-flex px-3 py-1 text-sm font-medium rounded-full {debt.debt_type === 'owed_to_me' ? 'bg-success/10 text-success' : 'bg-destructive/10 text-destructive'}">
											{debt.debt_type === 'owed_to_me' ? 'Owed to Me' : 'I Owe'}
										</span>
									</div>
									<div>
										<label class="block text-sm font-medium text-muted-foreground mb-1">Currency</label>
										<div class="text-sm text-foreground">{debt.currency}</div>
									</div>
								</div>

								{#if debt.description}
									<div>
										<label class="block text-sm font-medium text-muted-foreground mb-1">Description</label>
										<div class="text-sm text-foreground">{debt.description}</div>
									</div>
								{/if}

								<div>
									<label class="block text-sm font-medium text-muted-foreground mb-1">Created</label>
									<div class="text-sm text-foreground">{formatDate(debt.created_at)}</div>
								</div>
							</div>
						</div>
					</div>

					<!-- Financial Details -->
					<div class="space-y-6">
						<div>
							<h3 class="text-lg font-medium text-foreground mb-4">Financial Details</h3>
							<div class="space-y-4">
								<div class="grid grid-cols-2 gap-4">
									<div>
										<label class="block text-sm font-medium text-muted-foreground mb-1">Total Amount</label>
										<div class="text-lg font-semibold text-foreground">{formatCurrency(debt.total_amount, debt.currency)}</div>
									</div>
									<div>
										<label class="block text-sm font-medium text-muted-foreground mb-1">Remaining Balance</label>
										<div class="text-lg font-semibold {debt.remainingBalance > 0 ? 'text-warning' : 'text-success'}">
											{formatCurrency(debt.remainingBalance, debt.currency)}
										</div>
									</div>
								</div>

								<div>
									<label class="block text-sm font-medium text-muted-foreground mb-2">Payment Progress</label>
									<div class="w-full bg-muted rounded-full h-2">
										<div 
											class="bg-primary h-2 rounded-full transition-all duration-300" 
											style="width: {calculateProgress()}%"
										></div>
									</div>
									<div class="text-sm text-muted-foreground mt-1">{calculateProgress()}% paid</div>
								</div>

								<div class="grid grid-cols-2 gap-4">
									<div>
										<label class="block text-sm font-medium text-muted-foreground mb-1">Due Date</label>
										<div class="text-sm text-foreground">{formatDate(debt.dueDate)}</div>
									</div>
									<div>
										<label class="block text-sm font-medium text-muted-foreground mb-1">Installment Plan</label>
										<div class="text-sm text-foreground">{getInstallmentText(debt.installment_plan)}</div>
									</div>
								</div>

								{#if debt.nextPayment}
									<div>
										<label class="block text-sm font-medium text-muted-foreground mb-1">Next Payment</label>
										<div class="text-sm text-foreground">{formatDate(debt.nextPayment)}</div>
									</div>
								{/if}
							</div>
						</div>
					</div>
				</div>

				<!-- Payment History -->
				<div>
					<div class="flex items-center justify-between mb-4">
						<h3 class="text-lg font-medium text-foreground">Payment History</h3>
						<button 
							on:click={() => showPaymentForm = !showPaymentForm}
							class="btn-primary text-sm"
						>
							<svg class="w-4 h-4 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
								<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 6v6m0 0v6m0-6h6m-6 0H6"></path>
							</svg>
							Add Payment
						</button>
					</div>

					<!-- Add Payment Form -->
					{#if showPaymentForm}
						<div class="card p-4 mb-4">
							<h4 class="font-medium text-foreground mb-4">Record New Payment</h4>
							{#if error}
								<div class="mb-4 p-3 bg-destructive/10 border border-destructive/20 rounded-lg">
									<p class="text-destructive text-sm">{error}</p>
								</div>
							{/if}
							<div class="grid grid-cols-1 md:grid-cols-2 gap-4">
								<div>
									<label class="label">Amount</label>
									<input 
										type="number" 
										bind:value={newPayment.amount} 
										step="0.01" 
										min="0"
										class="input"
										placeholder="0.00"
									/>
								</div>
								<div>
									<label class="label">Payment Date</label>
									<input 
										type="date" 
										bind:value={newPayment.payment_date} 
										class="input"
									/>
								</div>
								<div>
									<label class="label">Payment Method</label>
									<select bind:value={newPayment.payment_method} class="input">
										<option value="cash">Cash</option>
										<option value="bank_transfer">Bank Transfer</option>
										<option value="check">Check</option>
										<option value="digital_wallet">Digital Wallet</option>
									</select>
								</div>
							</div>
							<div class="mt-4">
									<label class="label">Description (Optional)</label>
									<input 
										type="text" 
										bind:value={newPayment.description} 
										class="input"
										placeholder="Payment description"
									/>
							</div>

							<!-- Receipt Photo Upload -->
							<div class="mt-4">
								<label class="label">Receipt Photo (Optional)</label>
								<div class="border-2 border-dashed border-border rounded-lg p-4 text-center hover:border-primary/50 transition-colors">
									{#if newPayment.receiptPhoto}
										<!-- Photo preview -->
										<div class="relative inline-block">
											<img 
												src={URL.createObjectURL(newPayment.receiptPhoto)} 
												alt="Receipt preview" 
												class="w-24 h-24 object-cover rounded-lg"
											/>
											<button 
												type="button"
												on:click={removeReceiptPhoto}
												class="absolute -top-2 -right-2 bg-destructive text-destructive-foreground rounded-full w-6 h-6 flex items-center justify-center text-xs hover:bg-destructive/90"
											>
												×
											</button>
										</div>
									{:else}
										<!-- Upload prompt -->
										<div class="space-y-2">
											<input 
												type="file" 
												accept="image/*" 
												on:change={handleFileSelect}
												class="hidden" 
												id="receipt-upload"
											/>
											<label 
												for="receipt-upload" 
												class="cursor-pointer text-primary hover:text-primary/80"
											>
												Click to upload or drag and drop
											</label>
											<p class="text-xs text-muted-foreground">
												JPG, PNG, GIF, WebP up to 5MB
											</p>
										</div>
									{/if}
								</div>
							</div>
							<div class="flex justify-end space-x-3 mt-4">
								<button on:click={() => showPaymentForm = false} class="btn-secondary">
									Cancel
								</button>
								<button on:click={handleAddPayment} class="btn-primary">
									Add Payment
								</button>
							</div>
						</div>
					{/if}

					<!-- Payments Table -->
					{#if isLoading}
						<div class="card p-8 text-center">
							<div class="flex items-center justify-center space-x-2">
								<div class="animate-spin rounded-full h-6 w-6 border-b-2 border-primary"></div>
								<span class="text-muted-foreground">Loading payments...</span>
							</div>
						</div>
					{:else if error}
						<div class="card p-8 text-center">
							<div class="flex items-center justify-center space-x-2 mb-4">
								<svg class="w-8 h-8 text-destructive" fill="none" stroke="currentColor" viewBox="0 0 24 24">
									<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 8v4m0 4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"></path>
								</svg>
								<span class="text-destructive font-medium">Failed to load payments</span>
							</div>
							<p class="text-muted-foreground mb-4">{error}</p>
							<button on:click={loadPayments} class="btn-secondary">
								<svg class="w-4 h-4 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
									<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15"></path>
								</svg>
								Try Again
							</button>
						</div>
					{:else if payments.length > 0}
						<div class="card overflow-hidden">
							<div class="overflow-x-auto">
								<table class="w-full">
									<thead class="bg-muted/50 border-b border-border">
										<tr>
											<th class="px-4 py-3 text-left text-xs font-medium text-muted-foreground uppercase tracking-wider">Date</th>
											<th class="px-4 py-3 text-left text-xs font-medium text-muted-foreground uppercase tracking-wider">Amount</th>
											<th class="px-4 py-3 text-left text-xs font-medium text-muted-foreground uppercase tracking-wider">Status</th>
											<th class="px-4 py-3 text-left text-xs font-medium text-muted-foreground uppercase tracking-wider">Receipt</th>
											{#if debt.debt_type === 'owed_to_me'}
												<th class="px-4 py-3 text-left text-xs font-medium text-muted-foreground uppercase tracking-wider">Actions</th>
											{/if}
										</tr>
									</thead>
									<tbody class="bg-card divide-y divide-border">
										{#each payments as payment, index (payment.id || `payment-${index}`)}
											<tr>
												<td class="px-4 py-3 text-sm text-foreground">{formatDate(payment.payment_date)}</td>
												<td class="px-4 py-3 text-sm font-medium text-foreground">{formatCurrency(payment.amount, payment.currency || debt.currency)}</td>
												<td class="px-4 py-3">
													<span class="inline-flex px-2 py-1 text-xs font-medium rounded-full {getPaymentStatusClass(payment.status)}">
														{payment.status.charAt(0).toUpperCase() + payment.status.slice(1)}
													</span>
												</td>
												<td class="px-4 py-3">
													{#if payment.receipt_photo_url}
														<button 
															on:click={() => viewReceiptPhoto(payment.receipt_photo_url!)}
															class="w-16 h-16 rounded-lg overflow-hidden border border-border hover:border-primary/50 transition-colors"
															title="View receipt"
														>
															<img 
																src={payment.receipt_photo_url} 
																alt="Receipt" 
																class="w-full h-full object-cover"
															/>
														</button>
													{:else}
														<div class="w-16 h-16 rounded-lg border border-border flex items-center justify-center text-muted-foreground">
															<svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
																<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14m-6-6h.01M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z" />
															</svg>
														</div>
													{/if}
												</td>
												{#if debt.debt_type === 'owed_to_me'}
													<td class="px-4 py-3">
														{#if payment.status !== 'verified' && payment.status !== 'completed'}
															<button 
																on:click={() => verifyPayment(payment.id)}
																class="inline-flex items-center px-3 py-1.5 text-xs font-medium rounded-md bg-blue-100 text-blue-700 hover:bg-blue-200 transition-colors"
																title={payment.status === 'rejected' ? 'Reverify payment' : 'Verify payment'}
															>
																<svg class="w-3 h-3 mr-1" fill="none" stroke="currentColor" viewBox="0 0 24 24">
																	<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
																</svg>
																{payment.status === 'rejected' ? 'Reverify' : 'Verify'}
															</button>
														{:else}
															<span class="inline-flex items-center px-3 py-1.5 text-xs font-medium rounded-md bg-green-100 text-green-700">
																<svg class="w-3 h-3 mr-1" fill="none" stroke="currentColor" viewBox="0 0 24 24">
																	<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7" />
																</svg>
																Verified
															</span>
														{/if}
													</td>
												{/if}
											</tr>
										{/each}
									</tbody>
								</table>
							</div>
						</div>
					{:else}
						<div class="card p-8 text-center">
							<svg class="mx-auto w-12 h-12 text-muted-foreground mb-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
								<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"></path>
							</svg>
							<h4 class="text-lg font-medium text-foreground mb-2">No payments recorded</h4>
							<p class="text-muted-foreground mb-4">Start tracking payments by adding the first payment record.</p>
							<button on:click={() => showPaymentForm = true} class="btn-primary">
								Add First Payment
							</button>
						</div>
					{/if}
				</div>
			</div>
		</div>

		<!-- Footer Actions -->
		<div class="px-6 py-4 border-t border-border flex items-center justify-between">
			<div class="flex items-center space-x-3">
				<button on:click={editDebt} class="btn-secondary">
					<svg class="w-4 h-4 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
						<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z"></path>
					</svg>
					Edit Debt
				</button>
				<button on:click={deleteDebt} class="btn-danger">
					<svg class="w-4 h-4 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
						<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16"></path>
					</svg>
					Delete Debt
				</button>
			</div>
			<button on:click={closeModal} class="btn-primary">
				Close
			</button>
		</div>
	</div>
</div>

<!-- Receipt Photo Viewer -->
<ReceiptPhotoViewer
	photoUrl={selectedReceiptPhoto}
	isOpen={showReceiptViewer}
	on:close={() => { showReceiptViewer = false; selectedReceiptPhoto = ''; }}
/>
